# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.9.2/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.9.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/travis/build/Alkud/OTUS_HOMEWORK_11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/travis/build/Alkud/OTUS_HOMEWORK_11

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/cmake-3.9.2/bin/cpack --config ./CPackSourceConfig.cmake /home/travis/build/Alkud/OTUS_HOMEWORK_11/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/cmake-3.9.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/cmake-3.9.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.9.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.9.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.9.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.9.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/Alkud/OTUS_HOMEWORK_11/CMakeFiles /home/travis/build/Alkud/OTUS_HOMEWORK_11/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/Alkud/OTUS_HOMEWORK_11/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bulkasync

# Build rule for target.
bulkasync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bulkasync
.PHONY : bulkasync

# fast build rule for target.
bulkasync/fast:
	$(MAKE) -f CMakeFiles/bulkasync.dir/build.make CMakeFiles/bulkasync.dir/build
.PHONY : bulkasync/fast

#=============================================================================
# Target rules for targets named otus_hw_11_test

# Build rule for target.
otus_hw_11_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 otus_hw_11_test
.PHONY : otus_hw_11_test

# fast build rule for target.
otus_hw_11_test/fast:
	$(MAKE) -f CMakeFiles/otus_hw_11_test.dir/build.make CMakeFiles/otus_hw_11_test.dir/build
.PHONY : otus_hw_11_test/fast

#=============================================================================
# Target rules for targets named async

# Build rule for target.
async: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 async
.PHONY : async

# fast build rule for target.
async/fast:
	$(MAKE) -f async_command_processor/CMakeFiles/async.dir/build.make async_command_processor/CMakeFiles/async.dir/build
.PHONY : async/fast

bulkasync.o: bulkasync.cpp.o

.PHONY : bulkasync.o

# target to build an object file
bulkasync.cpp.o:
	$(MAKE) -f CMakeFiles/bulkasync.dir/build.make CMakeFiles/bulkasync.dir/bulkasync.cpp.o
.PHONY : bulkasync.cpp.o

bulkasync.i: bulkasync.cpp.i

.PHONY : bulkasync.i

# target to preprocess a source file
bulkasync.cpp.i:
	$(MAKE) -f CMakeFiles/bulkasync.dir/build.make CMakeFiles/bulkasync.dir/bulkasync.cpp.i
.PHONY : bulkasync.cpp.i

bulkasync.s: bulkasync.cpp.s

.PHONY : bulkasync.s

# target to generate assembly for a file
bulkasync.cpp.s:
	$(MAKE) -f CMakeFiles/bulkasync.dir/build.make CMakeFiles/bulkasync.dir/bulkasync.cpp.s
.PHONY : bulkasync.cpp.s

homework_11.o: homework_11.cpp.o

.PHONY : homework_11.o

# target to build an object file
homework_11.cpp.o:
	$(MAKE) -f CMakeFiles/bulkasync.dir/build.make CMakeFiles/bulkasync.dir/homework_11.cpp.o
	$(MAKE) -f CMakeFiles/otus_hw_11_test.dir/build.make CMakeFiles/otus_hw_11_test.dir/homework_11.cpp.o
.PHONY : homework_11.cpp.o

homework_11.i: homework_11.cpp.i

.PHONY : homework_11.i

# target to preprocess a source file
homework_11.cpp.i:
	$(MAKE) -f CMakeFiles/bulkasync.dir/build.make CMakeFiles/bulkasync.dir/homework_11.cpp.i
	$(MAKE) -f CMakeFiles/otus_hw_11_test.dir/build.make CMakeFiles/otus_hw_11_test.dir/homework_11.cpp.i
.PHONY : homework_11.cpp.i

homework_11.s: homework_11.cpp.s

.PHONY : homework_11.s

# target to generate assembly for a file
homework_11.cpp.s:
	$(MAKE) -f CMakeFiles/bulkasync.dir/build.make CMakeFiles/bulkasync.dir/homework_11.cpp.s
	$(MAKE) -f CMakeFiles/otus_hw_11_test.dir/build.make CMakeFiles/otus_hw_11_test.dir/homework_11.cpp.s
.PHONY : homework_11.cpp.s

otus_hw_11_test.o: otus_hw_11_test.cpp.o

.PHONY : otus_hw_11_test.o

# target to build an object file
otus_hw_11_test.cpp.o:
	$(MAKE) -f CMakeFiles/otus_hw_11_test.dir/build.make CMakeFiles/otus_hw_11_test.dir/otus_hw_11_test.cpp.o
.PHONY : otus_hw_11_test.cpp.o

otus_hw_11_test.i: otus_hw_11_test.cpp.i

.PHONY : otus_hw_11_test.i

# target to preprocess a source file
otus_hw_11_test.cpp.i:
	$(MAKE) -f CMakeFiles/otus_hw_11_test.dir/build.make CMakeFiles/otus_hw_11_test.dir/otus_hw_11_test.cpp.i
.PHONY : otus_hw_11_test.cpp.i

otus_hw_11_test.s: otus_hw_11_test.cpp.s

.PHONY : otus_hw_11_test.s

# target to generate assembly for a file
otus_hw_11_test.cpp.s:
	$(MAKE) -f CMakeFiles/otus_hw_11_test.dir/build.make CMakeFiles/otus_hw_11_test.dir/otus_hw_11_test.cpp.s
.PHONY : otus_hw_11_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package_source"
	@echo "... test"
	@echo "... package"
	@echo "... bulkasync"
	@echo "... rebuild_cache"
	@echo "... otus_hw_11_test"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... async"
	@echo "... bulkasync.o"
	@echo "... bulkasync.i"
	@echo "... bulkasync.s"
	@echo "... homework_11.o"
	@echo "... homework_11.i"
	@echo "... homework_11.s"
	@echo "... otus_hw_11_test.o"
	@echo "... otus_hw_11_test.i"
	@echo "... otus_hw_11_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

